_currentDirPath = "js/GemTD/components/"
include(_currentDirPath + "State.js");
include(_currentDirPath + "EnemyController.js");
include(_currentDirPath + "EventController.js");
include(_currentDirPath + "MoveController.js");
include(_currentDirPath + "GemController.js");
include(_currentDirPath + "AttackEnemy.js");
include(_currentDirPath + "ShellController.js");
include(_currentDirPath + "HealthBar.js");